### ISSUE TITLE
Date format issue in code

### ISSUE THREAD

**Issue by ClausSuperusers** [MicrosoftLearning/20483-Programming-in-C-Sharp#65]
When displaying date of birth, the lab uses the current locale (in my case Danish: dd-mm-yyyy).
When saving a student, the code uses "ParseExact", expecting a US format (mm/dd-yyyy), which results in an exception.

**Comment by asmalizaa** [comment]
I changed my PC date/time setting to match the expected format which is "MM/dd/yyyy" then only it works

**Comment by ken3d06** [comment]
Or if you do not want to change your PC settings, change sf.dateOfBirth.Text = student.DateOfBirth.ToString("d"); to  sf.dateOfBirth.Text = student.DateOfBirth.ToString("MM/dd/yyyy");

**Comment by corkwatchr** [comment]
In the case of an **Edit** or an **Insert**, I think the code should be changed to:
`student.DateOfBirth = DateTime.Parse(sf.dateOfBirth.Text);`
I don't know why the Lab 1 Solution lab is using the ParseExact() method. The Challenge lab simply tells the student to use Parse. The Solution lab should as well.

**Comment by JonGonard** [comment]
Changed every instance of DateTime.ParseExact to Parse
