### ISSUE TITLE
Mod02 - Lab 2

### ISSUE THREAD

**Issue by elamike** [MicrosoftLearning/20483-Programming-in-C-Sharp#66]
Hey guys,

I am using the Mod02 - Lab 2 for the Programming in C# - 20483C course.
Exercise 3: Saving Changes to the Class List
Task 3: Add exception handling to the code to catch concurrency, update, and general exceptions

While I am using the code for adding exception handling to the code to catch concurrency, update and general exceptions, it looks that OptimisticConcurrencyException not raising.
I am running 2 instances at the same time (1 from VS, 1 from the binary folder), I change the item from the VS, and then when I try to change it from the other instance, I can still change it again. 
Last change always wins which is wrong.

Did anybody experience the same issue ? 
Could you please validate/test the piece of code from your side ?
Why does OptimisticConcurrencyException or UpdateException not fire ? 
Should I need to use a specific version of EF ?

thanks,
Michael

**Comment by corkwatchr** [comment]
I think the table to be defined with an extra column for an automatic "data change" timestamp. I get the same results. I couldn't trigger the exception. Alternately, we can open a transaction in Serializable mode  for pessimistic locking.

**Comment by JonGonard** [comment]
Hi, sorry for the late response.

You're right, we were missing a transaction scope. I've added one, and the errors now occur.
