### ISSUE TITLE
Module 4 Ex. 2 Task 3 Step 7

### ISSUE THREAD

**Issue by XtremeLabsSupport** [MicrosoftLearning/20483-Programming-in-C-Sharp#67]
The solution provided and the instructions for the TestValidGrade TestMethod are incorrect causing this test method to fail the unit test.

The following command parses 01/01/2012 from a datetime to a string in doing so it becomes 1/1/2012.

GradesPrototype.Data.Grade grade = new GradesPrototype.Data.Grade(1, "01/01/2012", "Math", "A-", "Very good");

Simply changing the assert to the following allows the unit test to execute without errors.

Assert.AreEqual(grade.AssessmentDate, "1/1/2012");

The parse as far as I can tell happens in Grade.cs: line 41 of the solution. DateTime.ToString("d"); drops leading 0's.

**Comment by JonGonard** [comment]
Changed the parse method to culture invariant. Tests are green
