### ISSUE TITLE
Course setup guide missing

### ISSUE THREAD

**Issue by HubKen** [MicrosoftLearning/20483-Programming-in-C-Sharp#68]
Hi,

The SkillPipe manual for this course states:

This revision of the course does not include virtual machines. The minimum hardware and software requirements are detailed in the course's Setup Guide, at: https://github.com/MicrosoftLearning/20483-Programming-in-C-Sharp.

However, this guide seems to be missing.

Thanks,
KenS

**Comment by barucht** [comment]
Thanks, added it.
