### ISSUE TITLE
Missing Exercice On Module 6 

### ISSUE THREAD

**Issue by marjimgu** [MicrosoftLearning/20483-Programming-in-C-Sharp#70]
Hello,

On the book, presentations and OneNote notes it's stated that there are 3 exercices however on MD of the Lab Files and LAK there is only 2.

The missing exercise is  "Persisting the serialized grade to a File".

Reviewing the book the "Exercise 2: Previewing the grades reports" seems it was blended the the excersise 2 of the MD.

Maybe a warning can added to not cause confusion with the class on the documentation.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
