### ISSUE TITLE
Module 8 update

### ISSUE THREAD

**Issue by XtremeLabsSupport** [MicrosoftLearning/20483-Programming-in-C-Sharp#73]
In the new directory for Module 8 the following package folder is not found in the location listed. I am unable to find it anywhere in the new Allfiles. The new solution also wont run properly for Ex1, whereas the old GRades.WebDataService.svc that uses the Data.Services version 5.8.3.0 opens in Edge without issue.

In the Reference Manager – Grades.Web dialog box do the following steps:
   Click Projects,and then select Grades.DataModel.
   Click Browse.
   In the Select the files to reference dialog box, browse to the [Repository 
   Root]\Allfiles\Mod08\Labfiles\Starter\Exercise 1\packages\EntityFramework.5.0.0\lib\net45 folder, click 
   EntityFramework.dll, and click Add.
   Click OK.

**Comment by JonGonard** [comment]
Hi, Sorry for the late response.
I'm seeing the DataModel project in both the starter and solution folder, and the project compiles. Can you please provide more details?
