### ISSUE TITLE
Module 11 Wrong Password

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/20483-Programming-in-C-Sharp#74]
In Module 11: Upgrade the Grades Report | Task 3: Build and test the application | of Exercise 1 | Step 3 directs the end-user to put in a password of password but it should be password99.  

Thanks!

**Comment by mreherefortea** [comment]
The same error occurs in Exercise 2 | Task 1 | Step 7.

**Comment by JonGonard** [comment]
Hi, sorry for the late response.
I couldn't find the issue. Are you talking about the instructions MD files? If so, which one.
