### ISSUE TITLE
Module 2 Exercise 3 solution is not complete

### ISSUE THREAD

**Issue by nicktones** [MicrosoftLearning/20483-Programming-in-C-Sharp#78]
Module 2 exercise 2 does not actually look like it's a complete solution, as per the instructions. The data does not save back to the database.

**Comment by hamilton7** [comment]
Any update on this ?

**Comment by JonGonard** [comment]
Hi, I apologize for the lateness of my response.

I've checked the exercise (I suppose you meant exercise 3), and it looked alright to me. could you please elaborate on the issue?

Thanks

**Comment by hamilton7** [comment]
After you press the button "Save Changes" the changes do not save back to the database.

I am using the (localdb)\MSSQLLocalDB. The data is displayed correctly, however something goes wrong with the saveChanges_Click method.

**Comment by JonGonard** [comment]
These exceptions happened only on the save changes method?
That's odd, I haven't seen anything like that. Do you have Live Share on your VS? Or perhaps TeamViewer? I could connect to your session and try to debug it.

I will be available for it at around 6pm GMT, is that OK?

**Comment by JonGonard** [comment]
I think I've found the issue, fixed with commit f92f363a23eb870a73823270fed5cfede8cb4e09
Try to run the Module 2 Exercise 3 solution, please let me know if the issue persists.

**Comment by hamilton7** [comment]
Sorry for my late repose (due to the different time zone)

Problem solved!

I've just tested it and it works smoothly now. What was the issue ?

thank you very much,
MIchael


________________________________

**Comment by JonGonard** [comment]
Two things, 

The code created a `TransactionScope` but never used it, so the transaction remained opened. The `TransactionScope` was also created before the connection, which is what may have led to the 
"Invalid transaction state" exception. I've removed the `TransactionScope` completely from that exercise.

Also, The code opened the connection but never closed it, so I've closed it in the `Window_Unloaded` event.

**Comment by hamilton7** [comment]
Thanks a lot JonGonard.

Have a nice day ahead.

________________________________

**Comment by hamilton7** [comment]
Dear All,

In Module 8, Exercise 2 has following url
http://localhost:1655/Services/GradesWebDataService.svc/$metadata

However, every time we getting the below error:

[cid:9ba6da42-5211-4701-9658-2089774563d6]

[cid:2ae062f6-80f6-488a-93f7-2957d84ff65e]

Can you please assist ?

thanks,
Michalis


________________________________

**Comment by hamilton7** [comment]
Dear All,

In Module 8, Exercise 2 has following url
http://localhost:1655/Services/GradesWebDataService.svc/$metadata

However, every time we getting the below error:

[cid:9ba6da42-5211-4701-9658-2089774563d6]

[cid:2ae062f6-80f6-488a-93f7-2957d84ff65e]

Can you please assist ?

thanks,
Michalis

**Comment by JonGonard** [comment]
This issue is closed and the request is unrelated, I saw you've opened a new issue, please post all relevant data there
