### ISSUE TITLE
Module 8 Exercise 2

### ISSUE THREAD

**Issue by hamilton7** [MicrosoftLearning/20483-Programming-in-C-Sharp#81]
Dear All,

In Module 8, Exercise 2 has the following url:
http://localhost:1655/Services/GradesWebDataService.svc/$metadata

However, when we try to configure it (Add Service Reference) we are getting the below error:

![image](https://user-images.githubusercontent.com/1113110/68093817-570ae680-fea2-11e9-8d75-80a2ea3fbc78.png)

![image](https://user-images.githubusercontent.com/1113110/68093815-4e1a1500-fea2-11e9-9796-3866bc6e3969.png)

**Comment by hamilton7** [comment]
![image](https://user-images.githubusercontent.com/1113110/68094055-3a23e280-fea5-11e9-928e-ba3caba1879b.png)

**Comment by JonGonard** [comment]
Hi @hamilton7 

I've tried to connected to the service, and it worked fine. Are you sure you ran the service before trying to add it?

Do you have a more detailed than what you've posted?

**Comment by GhostyWombat** [comment]
@JonGonard I've just run into the exact same issue. What do you mean by 'ran the service before trying to add it'?

Sidenote: I've realised I do not have a 'Grades.WPF' project in my solution. Could this be causing the issue?

I've reloaded all my NuGet packages and rebuilt the solution.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
