### ISSUE TITLE
Module 7 Exercise 1: Creating an Entity Data Model fails depending on project template

### ISSUE THREAD

**Issue by Frits-Kuijk-OCICT** [MicrosoftLearning/20483-Programming-in-C-Sharp#84]
Step 3 lacks the specification of the requirement to create a new Class Library (.Net Framework) project to allow the ADO.NET Entity Data Model template to become available as an option in the Add New Item dialog on the project. A student could easily choose for the .NET Standard variant that will not show the particular new item template, especialy since it is listed as a later option.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
