### ISSUE TITLE
Database setup fails

### ISSUE THREAD

**Issue by Frits-Kuijk-OCICT** [MicrosoftLearning/20483-Programming-in-C-Sharp#85]
when I run the SetupSchoolDB.cmd no database is created.

**Comment by Frits-Kuijk-OCICT** [comment]
the location of the sqlcmd.exe file (under C:\Program Files\Microsoft SQL Swerver\) should be added to the PATH environment variable.
Setup issue?

**Comment by ChrisHowd** [comment]
MS is closing this issue.
