### ISSUE TITLE
Module 8 Exercise 1

### ISSUE THREAD

**Issue by GhostyWombat** [MicrosoftLearning/20483-Programming-in-C-Sharp#87]
The following folder does not exist in the repository? [Repository Root]\Allfiles\Mod08\Labfiles\Starter\Exercise 1\packages\EntityFramework.5.0.0\lib\net45

I need to reference it but I can't seem to find it? Maybe I'm doing something wrong or looking in the wrong place. Here is the exact part of the question:

"Add a reference to the **EntityFramework** assembly. This assembly is located in the [Repository Root]\Allfiles\Mod08\Labfiles\Starter\Exercise 1\packages\EntityFramework.5.0.0\lib\net45 folder."

Please advise. Thanks

**Comment by JonGonard** [comment]
Anything in the packages folder is from nuget. You need to perform Nuget restore and you'll be able to proceed.
