### ISSUE TITLE
.NET Core and C# 8

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/20483-Programming-in-C-Sharp#88]
As this training is based on the .NET Framework and an old version of Visual Studio, it would be useful to update it to .NET Core 3.1 and C# 8 and going forward to .NET 5.

I started on doing some updates in the dotnetcore3 branch of https://github.com/christiannagel/20483-Programming-in-C-Sharp, but don't have enough spare-time to update everything. It's a major change.

Because of the major changes that cannot be done all at once, a new branch in the MicrosoftLearning repository would be useful, probably also a complete new repository similar to the ASP.NET training.

Changes needed:

* Libraries to .NET Standard
* add dependency injection, logging, configuration (`Host` class)
* WPF applications to .NET Core WPF
* Entity Framework to EF Core
* WCF to Web API
* C# 8 syntax extensions

To update the WPF applications, [try-convert](https://github.com/dotnet/try-convert) is a useful tool.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
